### ISSUE TITLE
SampleClient not connecting to online brokers

### ISSUE THREAD

**Issue by chintan-mishra** [suvash/hulaaki#29]
While attempting to test Hulaaki on remote brokers the broker showed error. Here are few things that I tried. Firstly, I was using HiveMQ then Mosquitto broker for seeing how Hulaaki works.

`iex(1)> {:ok, pid} = SampleClient.start_link(%{})`
`{:ok, #PID<0.151.0>}`
`iex(2)> options = [client_id: "testID", host: "broker.hivemq.com", port: 1883, ssl: false]`
`[client_id: "testID", host: "broker.hivemq.com", port: 1883, ssl: false]`
`iex(3)> SampleClient.connect(pid, options)`
`{:error, :timeout}`
`iex(4)> options = [client_id: "testID", host: "test.mosquitto.org", port: 1883, ssl: false]`
`[client_id: "testID", host: "test.mosquitto.org", port: 1883, ssl: false]`
`iex(5)> SampleClient.connect(pid, options)`
`{:error, :timeout}`

After this, I added `tcp://` before the hostname. It resulted in receiving `nxdomain` error (Domain not found).

`iex(6)> options = [client_id: "testID", host: "tcp://broker.hivemq.com", port: 1883, ssl: false]`
`[client_id: "testID", host: "tcp://broker.hivemq.com", port: 1883, ssl: false]`
`iex(7)> SampleClient.connect(pid, options)`
`{:error, :nxdomain}`
`iex(8)> options = [client_id: "testID", host: "tcp://test.mosquitto.org", port: 1883, ssl: false]`
`[client_id: "testID", host: "tcp://test.mosquitto.org", port: 1883, ssl: false]`
`iex(9)> SampleClient.connect(pid, options)`
`{:error, :nxdomain}`

But the same SampleClient worked like a charm when I tried running it along with a broker(VerneMQ) on my local machine

`options = [client_id: "testID", host: "127.0.0.1", port: 1883, ssl: false]               `
`[client_id: "testID", host: "127.0.0.1", port: 1883, ssl: false]`
`iex(11)> SampleClient.connect(pid, options)`
`:ok
[message: %Hulaaki.Message.ConnAck{return_code: 0, session_present: 0,
  type: :CONNACK},
 state: %{connection: #PID<0.154.0>, keep_alive_interval: 100000,
   keep_alive_timer_ref: #Reference<0.442784578.1795424257.96752>, packet_id: 1,
   ping_response_timeout_interval: 200000, ping_response_timer_ref: nil}]`
`iex(12)> SampleClient.ping(pid)`
`:ok
[message: %Hulaaki.Message.PingResp{type: :PINGRESP},
 state: %{connection: #PID<0.154.0>, keep_alive_interval: 100000,
   keep_alive_timer_ref: #Reference<0.442784578.1795424257.96784>, packet_id: 1,
   ping_response_timeout_interval: 200000, ping_response_timer_ref: nil}]`

How to connect SampleClient to a remote broker?

**Comment by suvash** [comment]
@chintan-mishra There's nothing different between localhost and remote servers, as long as DNS can resolve the name and the server is available.
There's an easy way to test this functionality. Just run the tcp client test against the server. Could be the case that the server is not available when you were trying. (or timeouts because of where the server is located)
Clone this repo and run the tests as follows:
```
MQTT_HOST=broker.hivemq.com mix test test/hulaaki/client_tcp_test.exs
```
Works good when I run the above, so closing this. Make sure that the server is reachable and works within a reasonable timeout window.

**Comment by suvash** [comment]
also, in the examples you've posted above, you can clearly see the errors causing the issue. `:timeout` in the first one, and `:nxdomain` in the second (because `tcp://` is not correct).
Try increasing the timeout for your client. That should solve the issue. However, I'd recommend connecting to a broker that's closer to you.
